### ISSUE TITLE
oopss.. I got new issue

### ISSUE THREAD

**Issue by ytrsh** [zhuolikevin/Simple-online-chatting#2]
![ekran alintisi](https://user-images.githubusercontent.com/19870447/27840951-fcef4092-6105-11e7-885a-48dade55b436.PNG)
In left, i ran server.py, and in right, i ran client.py.  I got this error on the screenshot. 
I convert codes to python3 with **2to3.py** script. Can there any trouble about it?

**Comment by zhuolikevin** [comment]
I just ran it with python2 myself and it works.
I'm not so sure about how **2to3.py** works. And I do not use python3 that much. It may be some kind of conversion trouble, say type inconsistence? *...object, not str...* stuff.

**Comment by ytrsh** [comment]
i dont understand what you want but py3 codes in here 

Server.py = https://paste.ubuntu.com/25020554/
Client.py = https://paste.ubuntu.com/25020563/

**Comment by zhuolikevin** [comment]
Sorry for the late reply. **2to3.py** does not convert socket related codes properly.  *In Python 3, strings are Unicode, but when transmitting on the network, the data needs to be bytes strings instead.*

For example, in [Line 402](https://github.com/zhuolikevin/Simple-online-chatting/blob/master/Server.py#L402) in my Python 2 codes, we just send a message with
```python
conn.send('|' + 'Welcome to DiaosChat'.center(40,'-') + '|')
```

However, in Python 3, it should be
```python
message = '|' + 'Welcome to DiaosChat'.center(40,'-') + '|'
conn.sendall(message.encode('utf-8'))
```

Learn more [here](https://stackoverflow.com/questions/42612002/python-sockets-error-typeerror-a-bytes-like-object-is-required-not-str-with?answertab=votes#tab-top)

I'd suggest change all the `conn.send` in `Server.py` to `conn.sendall` and encode the message. Also, remember to decode message when receiving.

**Comment by ytrsh** [comment]
ok thankss
